In [21]:
import pandas as pd
import numpy as np
import datetime
seattle=pd.read_csv('./data/seattle/listings.csv')
boston=pd.read_csv('./data/boston/listings.csv')
seattle_calendar=pd.read_csv('./data/boston/calendar.csv')

droppedCols=['listing_url', 'scrape_id', 'last_scraped','name', 'summary',
       'space', 'description','neighborhood_overview',
       'notes','thumbnail_url', 'medium_url', 'picture_url', 'xl_picture_url']
seattle=seattle.drop(axis=1,columns=droppedCols)
seattle_calendar['month']=seattle_calendar['date'].map( lambda x: x.month if x)

AttributeError: 'str' object has no attribute 'month'

In [3]:
seattle_reviews=pd.read_csv('./data/boston/reviews.csv')
seattle_reviews.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,1178162,4724140,2013-05-21,4298113,Olivier,My stay at islam's place was really cool! Good...
1,1178162,4869189,2013-05-29,6452964,Charlotte,Great location for both airport and city - gre...
2,1178162,5003196,2013-06-06,6449554,Sebastian,We really enjoyed our stay at Islams house. Fr...
3,1178162,5150351,2013-06-15,2215611,Marine,The room was nice and clean and so were the co...
4,1178162,5171140,2013-06-16,6848427,Andrew,Great location. Just 5 mins walk from the Airp...

In [4]:
cat_df =seattle.select_dtypes(include=['object']) # Subset to a dataframe only holding the categorical columns

# Print how many categorical columns are in the dataframe - should be 147
cat_df.shape[1]

50

Remove all columns with blank values

In [5]:
seatle=seattle.dropna(axis=1,how='all')
seattle.columns

Index(['id', 'experiences_offered', 'transit', 'host_id', 'host_url',
       'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'street',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'city', 'state', 'zipcode', 'market',
       'smart_location', 'country_code', 'country', 'latitude', 'longitude',
       'is_location_exact', 'property_type', 'room_type', 'accommodates',
       'bathrooms', 'bedrooms', 'beds', 'bed_type', 'amenities', 'square_feet',
       'price', 'weekly_price', 'monthly_price', 'security_deposit',
       'cleaning_fee', 'guests_included', 'extra_people', 'minimum_nights',
       'maximum_nights', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'first_review', 'last_review', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'requires_license',
       'license', 'jurisdiction_names', 'instant_bookable',
       'cancellation_policy', 'require_guest_profile_picture',
       'require_guest_phone_verification', 'calculated_host_listings_count',
       'reviews_per_month'],
      dtype='object')

In [6]:
seattle[['neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed']]

     neighbourhood neighbourhood_cleansed neighbourhood_group_cleansed
0       Queen Anne        West Queen Anne                   Queen Anne
1       Queen Anne        West Queen Anne                   Queen Anne
2       Queen Anne        West Queen Anne                   Queen Anne
3       Queen Anne        West Queen Anne                   Queen Anne
4       Queen Anne        West Queen Anne                   Queen Anne
5       Queen Anne        West Queen Anne                   Queen Anne
6       Queen Anne        West Queen Anne                   Queen Anne
7       Queen Anne        West Queen Anne                   Queen Anne
8       Queen Anne        West Queen Anne                   Queen Anne
9       Queen Anne        West Queen Anne                   Queen Anne
10      Queen Anne        West Queen Anne                   Queen Anne
11      Queen Anne        West Queen Anne                   Queen Anne
12             NaN        West Queen Anne                   Queen Anne
13      Queen Anne        West Queen Anne                   Queen Anne
14      Queen Anne        West Queen Anne                   Queen Anne
15             NaN        West Queen Anne                   Queen Anne
16      Queen Anne        West Queen Anne                   Queen Anne
17      Queen Anne        West Queen Anne                   Queen Anne
18      Queen Anne        West Queen Anne                   Queen Anne
19      Queen Anne        West Queen Anne                   Queen Anne
20             NaN        West Queen Anne                   Queen Anne
21      Queen Anne        West Queen Anne                   Queen Anne
22      Queen Anne        West Queen Anne                   Queen Anne
23      Queen Anne        West Queen Anne                   Queen Anne
24      Queen Anne        West Queen Anne                   Queen Anne
25      Queen Anne        West Queen Anne                   Queen Anne
26      Queen Anne        West Queen Anne                   Queen Anne
27      Queen Anne        West Queen Anne                   Queen Anne
28      Queen Anne        West Queen Anne                   Queen Anne
29      Queen Anne        West Queen Anne                   Queen Anne
...            ...                    ...                          ...
3788       Fremont                Fremont          Other neighborhoods
3789       Fremont                Fremont          Other neighborhoods
3790       Fremont                Fremont          Other neighborhoods
3791       Fremont                Fremont          Other neighborhoods
3792       Fremont                Fremont          Other neighborhoods
3793       Fremont                Fremont          Other neighborhoods
3794       Fremont                Fremont          Other neighborhoods
3795           NaN                Fremont          Other neighborhoods
3796       Fremont                Fremont          Other neighborhoods
3797       Fremont                Fremont          Other neighborhoods
3798       Fremont                Fremont          Other neighborhoods
3799       Fremont                Fremont          Other neighborhoods
3800       Fremont                Fremont          Other neighborhoods
3801       Fremont                Fremont          Other neighborhoods
3802           NaN                Fremont          Other neighborhoods
3803       Fremont                Fremont          Other neighborhoods
3804       Fremont                Fremont          Other neighborhoods
3805       Fremont                Fremont          Other neighborhoods
3806       Fremont                Fremont          Other neighborhoods
3807   Wallingford                Fremont          Other neighborhoods
3808       Fremont                Fremont          Other neighborhoods
3809       Fremont                Fremont          Other neighborhoods
3810       Fremont                Fremont          Other neighborhoods
3811       Fremont                Fremont          Other neighborhoods
3812       Fremont                Fremont          Other neighborhoods
3813       Fremont                Fremont          Other neighborhoods
3814   Portage Bay            Portage Bay                 Capitol Hill
3815           NaN          Rainier Beach               Rainier Valley
3816           NaN           Madison Park                 Capitol Hill
3817    Queen Anne        East Queen Anne                   Queen Anne

[3818 rows x 3 columns]

In [7]:
host=seattle[['host_id', 'host_url',
       'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified']]
host.head()

,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified
0,956883,https://www.airbnb.com/users/show/956883,Maija,2011-08-11,"Seattle, Washington, United States","I am an artist, interior designer, and run a s...",within a few hours,96%,100%,f,https://a0.muscache.com/ac/users/956883/profil...,https://a0.muscache.com/ac/users/956883/profil...,Queen Anne,3.0,3.0,"['email', 'phone', 'reviews', 'kba']",t,t
1,5177328,https://www.airbnb.com/users/show/5177328,Andrea,2013-02-21,"Seattle, Washington, United States",Living east coast/left coast/overseas. Time i...,within an hour,98%,100%,t,https://a0.muscache.com/ac/users/5177328/profi...,https://a0.muscache.com/ac/users/5177328/profi...,Queen Anne,6.0,6.0,"['email', 'phone', 'facebook', 'linkedin', 're...",t,t
2,16708587,https://www.airbnb.com/users/show/16708587,Jill,2014-06-12,"Seattle, Washington, United States",i love living in Seattle. i grew up in the mi...,within a few hours,67%,100%,f,https://a1.muscache.com/ac/users/16708587/prof...,https://a1.muscache.com/ac/users/16708587/prof...,Queen Anne,2.0,2.0,"['email', 'phone', 'google', 'reviews', 'jumio']",t,t
3,9851441,https://www.airbnb.com/users/show/9851441,Emily,2013-11-06,"Seattle, Washington, United States",NaN,NaN,NaN,NaN,f,https://a2.muscache.com/ac/users/9851441/profi...,https://a2.muscache.com/ac/users/9851441/profi...,Queen Anne,1.0,1.0,"['email', 'phone', 'facebook', 'reviews', 'jum...",t,t
4,1452570,https://www.airbnb.com/users/show/1452570,Emily,2011-11-29,"Seattle, Washington, United States","Hi, I live in Seattle, Washington but I'm orig...",within an hour,100%,NaN,f,https://a0.muscache.com/ac/users/1452570/profi...,https://a0.muscache.com/ac/users/1452570/profi...,Queen Anne,2.0,2.0,"['email', 'phone', 'facebook', 'reviews', 'kba']",t,t

In [8]:
host.dtypes

host_id                        int64
host_url                      object
host_name                     object
host_since                    object
host_location                 object
host_about                    object
host_response_time            object
host_response_rate            object
host_acceptance_rate          object
host_is_superhost             object
host_thumbnail_url            object
host_picture_url              object
host_neighbourhood            object
host_listings_count          float64
host_total_listings_count    float64
host_verifications            object
host_has_profile_pic          object
host_identity_verified        object
dtype: object

In [9]:
location=seattle[['street',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'city', 'state', 'zipcode', 'market',
       'smart_location', 'country_code', 'country', 'latitude', 'longitude',
       'is_location_exact']]
location

,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,city,state,zipcode,market,smart_location,country_code,country,latitude,longitude,is_location_exact
0,"Gilman Dr W, Seattle, WA 98119, United States",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.636289,-122.371025,t
1,"7th Avenue West, Seattle, WA 98119, United States",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.639123,-122.365666,t
2,"West Lee Street, Seattle, WA 98119, United States",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.629724,-122.369483,t
3,"8th Avenue West, Seattle, WA 98119, United States",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.638473,-122.369279,t
4,"14th Ave W, Seattle, WA 98119, United States",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.632918,-122.372471,t
5,"West Comstock Street, Seattle, WA 98119, Unite...",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.630525,-122.366174,t
6,"10th Avenue West, Seattle, WA 98119, United St...",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.636605,-122.368519,t
7,"West Wheeler Street, Seattle, WA 98119, United...",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.640161,-122.375856,t
8,"Queen Anne Avenue North, Seattle, WA 98109, Un...",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98109,Seattle,"Seattle, WA",US,United States,47.632410,-122.357216,t
9,"7th Avenue West, Seattle, WA 98119, United States",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.637492,-122.366889,t
10,"1st Ave W, Seattle, WA 98119, United States",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.635482,-122.358478,t
11,"3rd Avenue West, Seattle, WA 98119, United States",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.637214,-122.360046,t
12,"West Howe Street, Seattle, WA 98119, United St...",NaN,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.635546,-122.373171,t
13,"West Prospect Street, Seattle, WA 98119, Unite...",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.629507,-122.367629,t
14,"7th Avenue West, Seattle, WA 98119, United States",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.639203,-122.365863,t
15,"12th Avenue West, Seattle, WA 98119, United St...",NaN,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.635650,-122.372893,f
16,"West Mercer Place, Seattle, WA 98119, United S...",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.626200,-122.366602,t
17,"12th Avenue West, Seattle, WA 98119, United St...",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.640646,-122.372406,t
18,"11th Avenue West, Seattle, WA 98119, United St...",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.639776,-122.372235,t
19,"1st Avenue West, Seattle, WA 98119, United States",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.636025,-122.358694,t
20,"West Olympic Place, Seattle, WA 98119, United ...",NaN,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.627940,-122.364959,f
21,"2nd Avenue West, Seattle, WA 98119, United States",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.636374,-122.361033,t
22,"1st Avenue West, Seattle, WA 98119, United States",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.635632,-122.358881,t
23,"West Galer Street, Seattle, WA 98119, United S...",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.633394,-122.371920,t
24,"10th Avenue West, Seattle, WA 98119, United St...",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.638517,-122.369581,t
25,"7th Avenue West, Seattle, WA 98119, United States",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.631397,-122.367767,t
26,"West McGraw Street, Seattle, WA 98119, United ...",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.638752,-122.367973,t
27,"West Wheeler Street, Seattle, WA 98119, United...",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.639266,-122.374726,t
28,"9th Avenue West, Seattle, WA 98119, United States",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.629907,-122.368948,t
29,"14th Avenue West, Seattle, WA 98119, United St...",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.639816,-122.374338,t
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3788,"Woodland Park Avenue North, Seattle, WA 98103,...",Fremont,Fremont,Other neighborhoods,Seattle,WA,98103,Seattle,"Seattle, WA",US,United States,47.656739,-122.344865,t
3789,"North 46th Street, Seattle, WA 98103, United S...",Fremont,Fremont,Other neighborhoods,Seattle,WA,98103,Seattle,"Seattle, WA",US,United States,47.661171,-122.349923,t
3790,"North 35th Street, Seattle, WA 98103, United S...",Fremont,Fremont,Other neighborhoods,Seattle,WA,98103,Seattle,"Seattle, WA",US,United States,47.649271,-122.347817,t
3791,"6th Avenue Northwest, Seattle, WA 98107, Unite...",Fremont,Fremont,Other neighborhoods,Seattle,WA,98107,Seattle,"Seattle, WA",US,United States,47.659149,-122.363466,t
3792,"North 46th Street, Seattle, WA 98103, United S...",Fremont,Fremont,Other neighborhoods,Seattle,WA,98103,Seattle,"Seattle, WA",US,United States,47.663040,-122.348499,t
3793,"Baker Avenue Northwest, Seattle, WA 98107, Uni...",Fremont,Fremont,Other neighborhoods,Seattle,WA,98107,Seattle,"Seattle, WA",US,United States,47.660056,-122.357683,t
3794,"Northwest Bowdoin Place, Seattle, WA 98107, Un...",Fremont,Fremont,Other neighborhoods,Seattle,WA,98107,Seattle,"Seattle, WA",US,United States,47.654199,-122.359987,t
3795,"Woodland Park Ave N, Seattle, WA 98103, United...",NaN,Fremont,Other neighborhoods,Seattle,WA,98103,Seattle,"Seattle, WA",US,United States,47.650124,-122.343283,f
3796,"NW 40th St, Seattle, WA 98107, United States",Fremont,Fremont,Other neighborhoods,Seattle,WA,98107,Seattle,"Seattle, WA",US,United States,47.656508,-122.360571,t
3797,"Phinney Avenue North, Seattle, WA 98103, Unite...",Fremont,Fremont,Other neighborhoods,Seattle,WA,98103,Seattle,"Seattle, WA",US,United States,47.658976,-122.354915,t
3798,"Midvale Avenue North, Seattle, WA 98103, Unite...",Fremont,Fremont,Other neighborhoods,Seattle,WA,98103,Seattle,"Seattle, WA",US,United States,47.655381,-122.343205,t
3799,"Dayton Avenue North, Seattle, WA 98103, United...",Fremont,Fremont,Other neighborhoods,Seattle,WA,98103,Seattle,"Seattle, WA",US,United States,47.652902,-122.352110,t
3800,"Linden Avenue North, Seattle, WA 98103, United...",Fremont,Fremont,Other neighborhoods,Seattle,WA,98103,Seattle,"Seattle, WA",US,United States,47.663613,-122.349519,t
3801,"1st Avenue Northwest, Seattle, WA 98107, Unite...",Fremont,Fremont,Other neighborhoods,Seattle,WA,98107,Seattle,"Seattle, WA",US,United States,47.657078,-122.358795,t
3802,"North 35th Street, Seattle, WA 98103, United S...",NaN,Fremont,Other neighborhoods,Seattle,WA,98103,Seattle,"Seattle, WA",US,United States,47.650765,-122.347787,f
3803,"Linden Avenue North, Seattle, WA 98103, United...",Fremont,Fremont,Other neighborhoods,Seattle,WA,98103,Seattle,"Seattle, WA",US,United States,47.661131,-122.349238,t
3804,"N 44th st, Seattle, WA 98103, United States",Fremont,Fremont,Other neighborhoods,Seattle,WA,98103,Seattle,"Seattle, WA",US,United States,47.660856,-122.352401,t
3805,"1st Avenue Northwest, Seattle, WA 98107, Unite...",Fremont,Fremont,Other neighborhoods,Seattle,WA,98107,Seattle,"Seattle, WA",US,United States,47.653158,-122.356285,t
3806,"Greenwood Avenue North, Seattle, WA 98103, Uni...",Fremont,Fremont,Other neighborhoods,Seattle,WA,98103,Seattle,"Seattle, WA",US,United States,47.656057,-122.354514,t
3807,"Stone Way North, Seattle, WA 98103, United States",Wallingford,Fremont,Other neighborhoods,Seattle,WA,98103,Seattle,"Seattle, WA",US,United States,47.654304,-122.342720,t
3808,"Dayton Avenue North, Seattle, WA 98103, United...",Fremont,Fremont,Other neighborhoods,Seattle,WA,98103,Seattle,"Seattle, WA",US,United States,47.662036,-122.350485,t
3809,"Albion Place North, Seattle, WA 98103, United ...",Fremont,Fremont,Other neighborhoods,Seattle,WA,98103,Seattle,"Seattle, WA",US,United States,47.648689,-122.343915,t
3810,"N Bowdoin Pl, Seattle, WA 98103, United States",Fremont,Fremont,Other neighborhoods,Seattle,WA,98103,Seattle,"Seattle, WA",US,United States,47.654205,-122.352604,t
3811,"Whitman Avenue North, Seattle, WA 98103, Unite...",Fremont,Fremont,Other neighborhoods,Seattle,WA,98103,Seattle,"Seattle, WA",US,United States,47.657898,-122.346692,t
3812,"Northwest 39th Street, Seattle, WA 98107, Unit...",Fremont,Fremont,Other neighborhoods,Seattle,WA,98107,Seattle,"Seattle, WA",US,United States,47.654516,-122.358124,t
3813,"Northwest 48th Street, Seattle, WA 98107, Unit...",Fremont,Fremont,Other neighborhoods,Seattle,WA,98107,Seattle,"Seattle, WA",US,United States,47.664295,-122.359170,t
3814,"Fuhrman Avenue East, Seattle, WA 98102, United...",Portage Bay,Portage Bay,Capitol Hill,Seattle,WA,98102,Seattle,"Seattle, WA",US,United States,47.649552,-122.318309,t
3815,"South Laurel Street, Seattle, WA 98178, United...",NaN,Rainier Beach,Rainier Valley,Seattle,WA,98178,Seattle,"Seattle, WA",US,United States,47.508453,-122.240607,f
3816,"43rd Avenue East, Seattle, WA 98112, United St...",NaN,Madison Park,Capitol Hill,Seattle,WA,98112,Seattle,"Seattle, WA",US,United States,47.632335,-122.275530,f
3817,"Westlake Avenue North, Seattle, WA 98109, Unit...",Queen Anne,East Queen Anne,Queen Anne,Seattle,WA,98109,Seattle,"Seattle, WA",US,United States,47.641186,-122.342085,t

In [10]:
apartment=seattle[['property_type', 'room_type', 'accommodates',
       'bathrooms', 'bedrooms', 'beds', 'bed_type', 'amenities', 'square_feet']]
apartment['amenities']=apartment['amenities'].map(lambda x: x.lstrip('{').rstrip('}').replace('\"','')) 
apartment['amenities'][1]

/Users/MX/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

'TV,Internet,Wireless Internet,Kitchen,Free Parking on Premises,Buzzer/Wireless Intercom,Heating,Family/Kid Friendly,Washer,Dryer,Smoke Detector,Carbon Monoxide Detector,First Aid Kit,Safety Card,Fire Extinguisher,Essentials'

In [11]:
from collections import defaultdict
def total_count(df, col1, col2, look_for):
    '''
    INPUT:
    df - the pandas dataframe you want to search
    col1 - the column name you want to look through
    col2 - the column you want to count values from
    look_for - a list of strings you want to search for in each row of df[col]

    OUTPUT:
    new_df - a dataframe of each look_for with the count of how often it shows up
    '''
    new_df = defaultdict(int)
    #loop through list of ed types
    for val in look_for:
        #loop through rows
        for idx in range(df.shape[0]):
            #if the ed type is in the row, add the devs
            if val in df[col1][idx]:
                new_df[val] += int(df[col2][idx])
    #clean up the resulting dataframe8
    new_df = pd.DataFrame(pd.Series(new_df)).reset_index()
    new_df.columns = [col1, col2]
    new_df.sort_values('count', ascending=False, inplace=True)
    return new_df

In [12]:
amenity = apartment['amenities'].value_counts().reset_index()
amenities=apartment['amenities'].str.get_dummies(sep=',')
amenities.columns

Index(['24-Hour Check-in', 'Air Conditioning', 'Breakfast',
       'Buzzer/Wireless Intercom', 'Cable TV', 'Carbon Monoxide Detector',
       'Cat(s)', 'Dog(s)', 'Doorman', 'Dryer', 'Elevator in Building',
       'Essentials', 'Family/Kid Friendly', 'Fire Extinguisher',
       'First Aid Kit', 'Free Parking on Premises', 'Gym', 'Hair Dryer',
       'Hangers', 'Heating', 'Hot Tub', 'Indoor Fireplace', 'Internet', 'Iron',
       'Kitchen', 'Laptop Friendly Workspace', 'Lock on Bedroom Door',
       'Other pet(s)', 'Pets Allowed', 'Pets live on this property', 'Pool',
       'Safety Card', 'Shampoo', 'Smoke Detector', 'Smoking Allowed',
       'Suitable for Events', 'TV', 'Washer', 'Washer / Dryer',
       'Wheelchair Accessible', 'Wireless Internet'],
      dtype='object')

In [13]:
possible_vals = ["TV","Cable TV"
                 ,"Internet","Wireless Internet","Air Conditioning","Kitchen","Heating","Family/Kid Friendly"
                 ,"Washer","Dryer"]

def clean_and_plot(df, title='Method of Educating Suggested', plot=True):
   
    
    amenity = df['amenities'].value_counts().reset_index()
    amenity.rename(columns={'index': 'method', 'amenities': 'count'}, inplace=True)
    amenity_df = total_count(amenity, 'method', 'count', possible_vals)

    amenity.set_index('method', inplace=True)
    if plot:
        (amenity_df/amenity_df.sum()).plot(kind='bar', legend=None);
        plt.title(title);
        plt.show()
    props_amenity_df = amenity_df/amenity_df.sum()
    return props_amenity_df
    
props_df = clean_and_plot(apartment)

ValueError: Cannot broadcast operands together.

In [ ]:
def strToMoney(df):
    columns=df.select_dtypes(include=['object']).columns
    
    for col in columns:
        df[col]=df[col].map(lambda x: float(x.lstrip('$').replace(',','')) if(isinstance(x, str)) else x)  
    return df

In [ ]:
cost=seattle[['price', 'weekly_price', 'monthly_price', 'security_deposit',
       'cleaning_fee', 'guests_included', 'extra_people', 'minimum_nights',
       'maximum_nights']]

In [ ]:
cost=strToMoney(cost)

In [ ]:

cost['weekly_price']=cost['weekly_price'].fillna(cost['price']*7)

In [ ]:
cost['monthly_price']=cost['monthly_price'].fillna(cost['price']*30.42)

In [ ]:
cost['security_deposit']=cost['security_deposit'].fillna(0)
cost['cleaning_fee']=cost['cleaning_fee'].fillna(0)

In [ ]:
cost.head()

In [ ]:
availability=seattle[['calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped']]
availability.head()

In [ ]:
reviews=seattle[['number_of_reviews',
        'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value']]
reviews

In [ ]:
policies=seattle[['requires_license',
       'instant_bookable',
       'cancellation_policy', 'require_guest_profile_picture',
       'require_guest_phone_verification', 'calculated_host_listings_count',
       'reviews_per_month']]
policies['reviews_per_month']=policies['reviews_per_month'].fillna(0)
policies=pd.get_dummies(policies)
policies